<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <UseMaui>True</UseMaui>
    <OutputType>Library</OutputType>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Common" Version="8.4.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusSchedule.Core\BusSchedule.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Maui.Controls" Version="10.0.71" />
  </ItemGroup>

</Project>
